export const siteCopy = {
  nav: [
    { id: "home", en: "Home", ar: "الرئيسية" },
    { id: "collections", en: "Collections", ar: "المجموعات" },
    { id: "factory", en: "Factory", ar: "الإنتاج" },
    { id: "about", en: "About", ar: "عن HONO" },
    { id: "contact", en: "Contact", ar: "تواصل معنا" },
  ],
  categoryNav: [
    { id: "home", en: "Home", ar: "الرئيسية" },
    { id: "collections", en: "Collections", ar: "المجموعات" },
    { id: "factory", en: "Factory", ar: "الإنتاج" },
    { id: "about", en: "About", ar: "عن HONO" },
    { id: "contact", en: "Contact", ar: "تواصل معنا" },
  ],
  megaMenus: {
    Home: {
      columns: [["Home", "Collections", "Factory", "About HONO", "Contact"]],
      featureCards: [
        { title: "Signature Collections", subtitle: "Explore styles", image: "modernAbayas" },
        { title: "Supply Support", subtitle: "Learn more", image: "factory" },
      ],
    },
    Collections: {
      columns: [
        [
          "Modern Abayas",
          "Elegant Jalabiyas",
          "Occasion Dresses",
          "Everyday Modest Wear",
        ],
        [
          "Abaya",
          "Jalabiya",
          "Long robe",
          "Modest dress",
          "Occasion wear",
          "Evening dress",
        ],
      ],
      featureCards: [
        { title: "Modern Abayas", subtitle: "WhatsApp inquiry", image: "modernAbayas" },
        { title: "Elegant Jalabiyas", subtitle: "View collection", image: "elegantJalabiyas" },
      ],
    },
    Factory: {
      columns: [
        [
          "Professional Clothing Resources",
          "Sample Development Support",
          "Small-Batch Production",
          "Quality Control & Packaging",
        ],
      ],
      featureCards: [{ title: "Factory Strength", subtitle: "Supply-chain support", image: "factory" }],
    },
    About: {
      columns: [["About HONO", "Riyadh-inspired elegance", "Modern modest fashion"]],
      featureCards: [{ title: "About HONO", subtitle: "Brand story", image: "hero" }],
    },
    Contact: {
      columns: [["WhatsApp", "Noon Store", "TikTok", "Instagram"]],
      featureCards: [{ title: "Connect", subtitle: "Official channels", image: "occasionDresses" }],
    },
  },
  copy: {
    en: {
      languageLabel: "العربية",
      announcementPrimary: "Modern modest fashion for Saudi Arabia and the Middle East",
      announcementSecondary: "Product inquiries through WhatsApp, Noon, TikTok and Instagram",
      topOffer: "HONO MODERN MODEST FASHION",
      regionLabel: "INT",
      heroEyebrow: "Saudi & Middle East Modestwear",
      heroCampaignTitle: "RIYADH",
      heroCampaignSubtitle: "INSPIRED MODEST FASHION",
      heroTitle: "Riyadh-Inspired Modest Fashion",
      heroSubtitle:
        "HONO creates elegant long robes, modern abayas and modest occasion dresses for women who value style, comfort and modesty.",
      whatsapp: "Contact on WhatsApp",
      noon: "Shop on Noon",
      noonStore: "Noon Store",
      whatsappLabel: "WhatsApp",
      noonLabel: "Noon Store",
      tiktokLabel: "TikTok",
      instagramLabel: "Instagram",
      heroImageKicker: "Modern abayas, jalabiyas and occasion dresses",
      collectionsEyebrow: "Signature Collections",
      collectionsTitle: "Signature Collections",
      collectionsIntro:
        "Explore HONO's modest fashion styles designed for everyday elegance, special occasions and modern Middle Eastern wardrobes.",
      inquiry: "WhatsApp Inquiry",
      factoryEyebrow: "Factory & Supply Chain Strength",
      factoryTitle: "Factory & Supply Chain Strength",
      factoryIntro:
        "HONO works with professional clothing factory resources and experienced production partners to support reliable modest fashion development.",
      factoryImageLabel: "Supply-chain support",
      factoryOriginLabel: "Professional modestwear development",
      aboutEyebrow: "About HONO",
      aboutTitle: "About HONO",
      aboutBody:
        "HONO is a women's fashion brand focused on modest dresses, abayas, jalabiyas and elegant occasion wear for Saudi Arabia and the Middle East. We combine graceful design, comfortable fabrics and reliable supply-chain support to serve modern women who value elegance, modesty and everyday confidence.",
      contactEyebrow: "Contact & Social Links",
      contactTitle: "Connect with HONO",
      contactIntro:
        "Discover our latest styles, contact us for product inquiries, or visit our official sales and social channels.",
      footer: "HONO - Modern Modest Fashion for Saudi Arabia & the Middle East.",
      trustFit: "Modern modest fashion",
      trustBatch: "Reliable supply-chain support",
      trustOrigin: "Designed for Saudi Arabia and the Middle East",
      promiseOne: "Modern modest fashion for women who value style, comfort and modesty.",
      promiseTwo: "Professional clothing resources and experienced production partners.",
      serviceReturns: "WhatsApp inquiry support",
      serviceFit: "Style, size and length guidance",
      serviceSince: "Reliable modest fashion development",
      softLayersHeading: "Modern modest styles for everyday elegance",
      softLayersIntro:
        "A refined edit of abayas, jalabiyas and modest long dresses for daily wear, special moments and modern Middle Eastern wardrobes.",
      softLayersPrimary: "Shop Jalabiyas",
      softLayersSecondary: "Shop Abayas",
      storyEyebrow: "Brand story",
      storyTitle: "Modern modest fashion with reliable supply-chain support",
      storyBody:
        "HONO combines graceful design, comfortable fabrics and professional production resources to serve women who value elegance, modesty and everyday confidence.",
      storyPointOne: "Modern modest fashion",
      storyPointTwo: "Professional clothing resources",
      storyPointThree: "Small-batch production support",
      footerShopTitle: "Collections",
      footerBrandTitle: "HONO",
      footerSupportTitle: "Contact",
      footerNewsletter: "Discover our latest styles, contact us for product inquiries, or visit our official sales and social channels.",
      fitTitle: "Elegant long robes, modern abayas and modest occasion dresses.",
      fitBody:
        "HONO creates modest fashion for women who value style, comfort and modesty.",
      fitBannerTitle: "STYLE COMFORT MODESTY",
      shopNow: "Shop on Noon",
      newBadge: "New",
      megaFallback:
        "Explore HONO modest fashion collections and contact us for product inquiries.",
      categoryHeading: "Shop by category",
      trendingEyebrow: "Signature Collections",
      trendingTitle: "Signature Collections",
      lookbookHeading: "HONO edit",
      lookbookIntro:
        "Modern modest fashion designed for everyday elegance, special occasions and Middle Eastern wardrobes.",
      discoverHeading: "Discover more",
      discoverNew: "Collections",
      discoverNewText: "Explore HONO's modest fashion styles for everyday elegance and special occasions.",
      discoverAbout: "About HONO",
      discoverAboutText: "Learn about HONO's focus on graceful design, comfortable fabrics and reliable supply-chain support.",
      discoverFactory: "Factory strength",
      discoverFactoryText: "See professional clothing resources, sample development, small-batch production and quality support.",
      brandElegant: "Elegant",
      brandModest: "Modest",
      brandReliable: "Reliable",
    },
    ar: {
      languageLabel: "English",
      announcementPrimary: "أزياء محتشمة عصرية للمملكة العربية السعودية والشرق الأوسط",
      announcementSecondary: "استفسارات المنتجات عبر واتساب ونون وتيك توك وإنستغرام",
      topOffer: "HONO أزياء محتشمة عصرية",
      regionLabel: "INT",
      heroEyebrow: "أزياء محتشمة للسعودية والشرق الأوسط",
      heroCampaignTitle: "الرياض",
      heroCampaignSubtitle: "أزياء محتشمة مستوحاة من الأناقة",
      heroTitle: "أزياء محتشمة مستوحاة من أناقة الرياض",
      heroSubtitle:
        "تصمّم HONO عبايات عصرية، جلابيات أنيقة وفساتين محتشمة للمناسبات، للمرأة التي تقدّر الأناقة والراحة والاحتشام.",
      whatsapp: "تواصلي عبر واتساب",
      noon: "تسوّقي عبر نون",
      noonStore: "متجر نون",
      whatsappLabel: "واتساب",
      noonLabel: "متجر نون",
      tiktokLabel: "تيك توك",
      instagramLabel: "إنستغرام",
      heroImageKicker: "عبايات عصرية، جلابيات وفساتين للمناسبات",
      collectionsEyebrow: "مجموعاتنا المميزة",
      collectionsTitle: "مجموعاتنا المميزة",
      collectionsIntro:
        "اكتشفي تصاميم HONO المحتشمة المصممة للأناقة اليومية، والمناسبات الخاصة، وخزانة المرأة العصرية في الشرق الأوسط.",
      inquiry: "استفسار عبر واتساب",
      factoryEyebrow: "قوة الإنتاج وسلسلة التوريد",
      factoryTitle: "قوة الإنتاج وسلسلة التوريد",
      factoryIntro:
        "تعمل HONO مع موارد إنتاج ملابس احترافية وشركاء تصنيع ذوي خبرة لدعم تطوير أزياء محتشمة موثوقة.",
      factoryImageLabel: "دعم سلسلة التوريد",
      factoryOriginLabel: "تطوير أزياء محتشمة باحترافية",
      aboutEyebrow: "عن HONO",
      aboutTitle: "عن HONO",
      aboutBody:
        "HONO هي علامة أزياء نسائية تركز على الفساتين المحتشمة، العبايات، الجلابيات وملابس المناسبات الأنيقة للمملكة العربية السعودية والشرق الأوسط. نجمع بين التصميم الراقي، الأقمشة المريحة ودعم سلسلة التوريد الموثوق لخدمة المرأة العصرية التي تقدّر الأناقة، الاحتشام والثقة اليومية.",
      contactEyebrow: "التواصل والروابط الاجتماعية",
      contactTitle: "تواصلي مع HONO",
      contactIntro:
        "اكتشفي أحدث تصاميمنا، تواصلي معنا للاستفسار عن المنتجات، أو زوري قنوات البيع والتواصل الرسمية الخاصة بنا.",
      footer: "HONO — أزياء محتشمة عصرية للمملكة العربية السعودية والشرق الأوسط.",
      trustFit: "أزياء محتشمة عصرية",
      trustBatch: "دعم موثوق لسلسلة التوريد",
      trustOrigin: "مصممة للسعودية والشرق الأوسط",
      promiseOne: "أزياء محتشمة عصرية للمرأة التي تقدّر الأناقة والراحة والاحتشام.",
      promiseTwo: "موارد إنتاج ملابس احترافية وشركاء تصنيع ذوو خبرة.",
      serviceReturns: "دعم الاستفسار عبر واتساب",
      serviceFit: "إرشاد الأسلوب والمقاسات والأطوال",
      serviceSince: "تطوير موثوق للأزياء المحتشمة",
      softLayersHeading: "تصاميم محتشمة عصرية للأناقة اليومية",
      softLayersIntro:
        "اختيار راق من العبايات والجلابيات والفساتين الطويلة المحتشمة للإطلالات اليومية واللحظات الخاصة وخزانة المرأة العصرية في الشرق الأوسط.",
      softLayersPrimary: "تسوّقي الجلابيات",
      softLayersSecondary: "تسوّقي العبايات",
      storyEyebrow: "قصة العلامة",
      storyTitle: "أزياء محتشمة عصرية بدعم موثوق لسلسلة التوريد",
      storyBody:
        "تجمع HONO بين التصميم الراقي، الأقمشة المريحة وموارد الإنتاج الاحترافية لخدمة المرأة التي تقدّر الأناقة، الاحتشام والثقة اليومية.",
      storyPointOne: "أزياء محتشمة عصرية",
      storyPointTwo: "موارد إنتاج احترافية",
      storyPointThree: "دعم إنتاج بكميات صغيرة",
      footerShopTitle: "المجموعات",
      footerBrandTitle: "HONO",
      footerSupportTitle: "تواصل",
      footerNewsletter: "اكتشفي أحدث تصاميمنا أو تواصلي معنا للاستفسار عن المنتجات عبر قنواتنا الرسمية.",
      fitTitle: "عبايات عصرية، جلابيات أنيقة وفساتين محتشمة للمناسبات.",
      fitBody:
        "تصمّم HONO أزياء محتشمة للمرأة التي تقدّر الأناقة والراحة والاحتشام.",
      fitBannerTitle: "أناقة راحة احتشام",
      shopNow: "تسوّقي عبر نون",
      newBadge: "جديد",
      megaFallback:
        "اكتشفي مجموعات HONO للأزياء المحتشمة وتواصلي معنا للاستفسار عن المنتجات.",
      categoryHeading: "تسوقي حسب التصنيف",
      trendingEyebrow: "مجموعاتنا المميزة",
      trendingTitle: "مجموعاتنا المميزة",
      lookbookHeading: "اختيارات HONO",
      lookbookIntro:
        "أزياء محتشمة عصرية مصممة للأناقة اليومية والمناسبات الخاصة وخزانة المرأة في الشرق الأوسط.",
      discoverHeading: "اكتشفي المزيد",
      discoverNew: "المجموعات",
      discoverNewText: "اكتشفي تصاميم HONO المحتشمة للأناقة اليومية والمناسبات الخاصة.",
      discoverAbout: "عن HONO",
      discoverAboutText: "تعرفي على تركيز HONO على التصميم الراقي والأقمشة المريحة ودعم سلسلة التوريد الموثوق.",
      discoverFactory: "قوة الإنتاج",
      discoverFactoryText: "شاهدي موارد الإنتاج الاحترافية، تطوير العينات، الإنتاج بكميات صغيرة ودعم الجودة.",
      brandElegant: "أنيق",
      brandModest: "محتشم",
      brandReliable: "موثوق",
    },
  },
  products: [
    {
      key: "modernAbayas",
      title: { en: "Modern Abayas", ar: "عبايات عصرية" },
      description: {
        en: "Elegant abayas with clean silhouettes, refined details and a modest fit for daily wear and special moments.",
        ar: "عبايات أنيقة بقصّات نظيفة وتفاصيل راقية وتصميم محتشم يناسب الإطلالات اليومية واللحظات الخاصة.",
      },
      price: { en: "WhatsApp Inquiry", ar: "استفسار عبر واتساب" },
      categoryCta: { en: "Modern Abayas", ar: "عبايات عصرية" },
    },
    {
      key: "elegantJalabiyas",
      title: { en: "Elegant Jalabiyas", ar: "جلابيات أنيقة" },
      description: {
        en: "Graceful jalabiyas inspired by Middle Eastern elegance, designed for comfort, beauty and refined occasions.",
        ar: "جلابيات راقية مستوحاة من أناقة الشرق الأوسط، مصممة لتجمع بين الراحة والجمال والمظهر المتزن.",
      },
      price: { en: "WhatsApp Inquiry", ar: "استفسار عبر واتساب" },
      categoryCta: { en: "Elegant Jalabiyas", ar: "جلابيات أنيقة" },
    },
    {
      key: "occasionDresses",
      title: { en: "Occasion Dresses", ar: "فساتين للمناسبات" },
      description: {
        en: "Modest long dresses with feminine details, suitable for weddings, gatherings, evening events and celebrations.",
        ar: "فساتين طويلة محتشمة بتفاصيل أنثوية، مناسبة لحفلات الزفاف، التجمعات، السهرات والمناسبات الخاصة.",
      },
      price: { en: "WhatsApp Inquiry", ar: "استفسار عبر واتساب" },
      categoryCta: { en: "Occasion Dresses", ar: "فساتين للمناسبات" },
    },
    {
      key: "everydayModestWear",
      title: { en: "Everyday Modest Wear", ar: "أزياء محتشمة يومية" },
      description: {
        en: "Comfortable and stylish modest pieces designed for daily dressing with a polished, modern look.",
        ar: "قطع محتشمة مريحة وأنيقة مصممة للإطلالات اليومية بأسلوب عصري ومرتب.",
      },
      price: { en: "WhatsApp Inquiry", ar: "استفسار عبر واتساب" },
      categoryCta: { en: "Everyday Modest Wear", ar: "أزياء محتشمة يومية" },
    },
  ],
  strengths: [
    {
      title: { en: "Professional Clothing Resources", ar: "موارد إنتاج احترافية" },
      description: {
        en: "Access to experienced clothing production resources for women's dresses, abayas and modest long robes.",
        ar: "إمكانية الوصول إلى موارد إنتاج ملابس ذات خبرة في فساتين النساء، العبايات والقطع الطويلة المحتشمة.",
      },
    },
    {
      title: { en: "Sample Development Support", ar: "دعم تطوير العينات" },
      description: {
        en: "Support for sample development, style adjustment and product improvement based on market needs.",
        ar: "دعم في تطوير العينات، تعديل التصاميم وتحسين المنتجات بناءً على احتياجات السوق.",
      },
    },
    {
      title: { en: "Small-Batch Production", ar: "إنتاج بكميات صغيرة" },
      description: {
        en: "Flexible small-batch production support for new styles, market testing and seasonal collections.",
        ar: "دعم مرن للإنتاج بكميات صغيرة لاختبار التصاميم الجديدة، السوق والمجموعات الموسمية.",
      },
    },
    {
      title: { en: "Quality Control & Packaging", ar: "فحص الجودة والتغليف" },
      description: {
        en: "Attention to product finishing, quality checking and export-ready packaging for cross-border sales.",
        ar: "اهتمام بتشطيب المنتج، فحص الجودة والتغليف الجاهز للتصدير والبيع عبر الحدود.",
      },
    },
  ],
  factoryStats: [
    { value: "4", en: "Supply-chain strengths", ar: "نقاط قوة في سلسلة التوريد" },
    { value: "QC", en: "Quality support", ar: "دعم الجودة" },
    { value: "B2B", en: "Cross-border ready", ar: "جاهز للبيع عبر الحدود" },
  ],
  productionFlow: [
    { en: "Professional clothing resources", ar: "موارد إنتاج احترافية" },
    { en: "Sample development support", ar: "دعم تطوير العينات" },
    { en: "Small-batch production", ar: "إنتاج بكميات صغيرة" },
    { en: "Quality control and packaging", ar: "فحص الجودة والتغليف" },
  ],
};
